services:
  openrefine:
    image: ghcr.io/openrefine/containers:master
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: master
    environment:
      REFINE_MEMORY: 2000M
      REFINE_MIN_MEMORY: 2000M
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3333
      published: 3333
      protocol: tcp
    volumes:
    - type: bind
      source: ./workspace
      target: /workspace
      bind:
        create_host_path: true
networks:
  default:
    name: openrefine_default
